### ISSUE TITLE
Lesson 1 to-do list

### ISSUE THREAD

**Issue by JohnAlbin** [NeihuCode/hello-world#3]
### Install software
* [x] Install Atom. https://atom.io/
* [x] Install GitKraken. https://www.gitkraken.com/
* [x] Optional: install Mac OS X command line tools. `xcode-select --install`

### Set up GitHub
* [x] Create GitHub account. https://github.com/join
* [x] Join **NeihuCode** organization on GitHub.
* [x] Fork/clone hello-world repository. https://github.com/neihucode/hello-world
* [ ] Copy the contents of `README.md` to a new issue in your repo.
* [ ] Change Settings -> GitHub Pages -> Source: `master branch /docs folder`

### Learn some Git, some HTML, some CSS
* [ ] View your new website. `*[your github account name]*.github.io/hello-world/`
* [ ] On GitHub, edit docs/index.html; add `<head><title>`. Save your change as a **commit**.
* [ ] Clone your GitHub repo with **GitKraken** app.
* [ ] Open your project files with **Atom**. ~/Sites/hello-world
* [ ] Edit docs/index.html; change `<p>` to `<h1>` and add paragraph of text.
* [ ] **Commit** your changes.
* [ ] **Push** your changes to GitHub and reload your website.
* [ ] Edit docs/index.html; add a `<link rel="stylesheet" href="css/styles.css">`. Create css folder and a css/styles.css file.
* [ ] Edit css/styles.css; add h1 hover styling.

### Learn Git branching and JavaScript.
* [ ] **Merge** the **branch** from your new pull request; it adds HTML and images.
* [ ] **Pull** the new changes from GitHub to your computer (using **GitKraken**).
* [ ] Learn about the new `<figure>`, `<figcaption>` and `<img>` HTML elements.
* [ ] Learn about the jQuery library that the pull request added. In your browser's console, run: `$('.carousel').slideToggle(5000)` which is documented at: http://api.jquery.com/slideToggle/
* [ ] Add Slick carousel to your project. Follow instructions under  "Example using jsDelivr" of https://github.com/kenwheeler/slick/ to add `link` and `script` tags to CSS and JS files.
